# Generated by Django 4.1.13 on 2025-12-14 04:35

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipDues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Year for the dues')),
                ('month', models.PositiveIntegerField(help_text='Month for the dues (1-12)')),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Amount due (₹10 per couple)', max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('due_date', models.DateField(help_text='Due date for payment')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_dues', to='membership.family')),
            ],
            options={
                'verbose_name': 'Membership Due',
                'verbose_name_plural': 'Membership Dues',
                'ordering': ['-year', '-month', 'family__name'],
                'unique_together': {('family', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('upi', 'UPI')], max_length=10)),
                ('receipt_number', models.CharField(editable=False, help_text='Auto-generated receipt number', max_length=20, unique=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Payment notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='membership.family')),
                ('membership_dues', models.ManyToManyField(blank=True, help_text='Dues covered by this payment', related_name='payments', to='membership.membershipdues')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
