# Generated by Django 4.2.27 on 2025-12-16 12:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_membershipdues_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipdues',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Amount due (matches System Settings)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='vitalrecord',
            name='record_type',
            field=models.CharField(choices=[('birth', 'Birth'), ('death', 'Death'), ('nikah', 'Nikah (Marriage)'), ('janazah', 'Janazah (Funeral)'), ('aqiqah', 'Aqiqah'), ('shahada', 'Shahada'), ('other', 'Other')], max_length=20),
        ),
    ]
