# Generated by Django 4.2.27 on 2025-12-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_membershipdues_amount_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='aadhaar_no',
            field=models.CharField(blank=True, max_length=12, verbose_name='Aadhaar Card No'),
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, help_text='Personal address if different from family'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_head_of_family',
            field=models.BooleanField(default=False, help_text='Is this person the head of the family?'),
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widowed'), ('D', 'Divorced')], max_length=1),
        ),
        migrations.AddField(
            model_name='member',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
