# Generated by Django 4.2.27 on 2025-12-19 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('membership', '0004_member_aadhaar_no_member_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
