# Generated by Django 4.2.27 on 2026-01-06 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_member_blood_group_member_city_member_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='family',
        ),
    ]
