# Generated by Django 4.2.27 on 2026-01-06 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_add_dropdown_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='city_dropdown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.city', verbose_name='City (Dropdown)'),
        ),
        migrations.AddField(
            model_name='member',
            name='country_dropdown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.country', verbose_name='Country (Dropdown)'),
        ),
        migrations.AddField(
            model_name='member',
            name='postal_code_dropdown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.postalcode', verbose_name='Postal Code (Dropdown)'),
        ),
        migrations.AddField(
            model_name='member',
            name='state_dropdown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.state', verbose_name='State (Dropdown)'),
        ),
        migrations.AddField(
            model_name='member',
            name='taluk_dropdown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.taluk', verbose_name='Taluk (Dropdown)'),
        ),
        migrations.AddField(
            model_name='member',
            name='ward_no_dropdown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.ward', verbose_name='Ward No (Dropdown)'),
        ),
    ]
