# Generated by Django 4.2.27 on 2026-01-07 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0013_member_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='city',
        ),
        migrations.RemoveField(
            model_name='member',
            name='country',
        ),
        migrations.RemoveField(
            model_name='member',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='member',
            name='state',
        ),
        migrations.RemoveField(
            model_name='member',
            name='taluk',
        ),
        migrations.RemoveField(
            model_name='member',
            name='ward_no',
        ),
        migrations.AlterField(
            model_name='houseregistration',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.city'),
        ),
        migrations.AlterField(
            model_name='houseregistration',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.country'),
        ),
        migrations.AlterField(
            model_name='houseregistration',
            name='house_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='houseregistration',
            name='house_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='houseregistration',
            name='postal_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.postalcode'),
        ),
        migrations.AlterField(
            model_name='houseregistration',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.state'),
        ),
        migrations.AlterField(
            model_name='houseregistration',
            name='taluk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.taluk'),
        ),
        migrations.AlterField(
            model_name='houseregistration',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.ward'),
        ),
    ]
