# Generated by Django 4.2.27 on 2026-01-07 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0014_remove_member_city_remove_member_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="houseregistration",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="membership.city"
            ),
        ),
        migrations.AlterField(
            model_name="houseregistration",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="membership.country"
            ),
        ),
        migrations.AlterField(
            model_name="houseregistration",
            name="postal_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="membership.postalcode"
            ),
        ),
        migrations.AlterField(
            model_name="houseregistration",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="membership.state"
            ),
        ),
        migrations.AlterField(
            model_name="houseregistration",
            name="taluk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="membership.taluk"
            ),
        ),
        migrations.AlterField(
            model_name="houseregistration",
            name="ward",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="membership.ward"
            ),
        ),
    ]
