# Generated by Django 4.2.27 on 2026-01-08 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0015_auto_20260107_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='house',
        ),
        migrations.AddField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='membership.member'),
        ),
    ]
