# Generated by Django 4.2.27 on 2026-01-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0016_remove_payment_house_payment_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseregistration',
            name='area',
            field=models.CharField(blank=True, help_text='Area name or locality', max_length=200),
        ),
    ]
