# Generated by Django 4.2.27 on 2026-01-13 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0016_remove_payment_house_payment_member'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(blank=True, help_text='For non-member donations, enter donor name here', max_length=200),
        ),
        migrations.AlterField(
            model_name='donation',
            name='member',
            field=models.ForeignKey(blank=True, help_text='Select a member, or leave blank for non-member donations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='membership.member'),
        ),
    ]
