# Generated by Django 4.2.27 on 2026-01-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_add_donor_name_to_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the person/entity related to this expense', max_length=200),
        ),
    ]
