# Generated by Django 4.1.13 on 2025-12-13 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit_type', models.CharField(choices=[('apartment', 'Apartment'), ('office', 'Office Space'), ('hall', 'Community Hall'), ('parking', 'Parking Space'), ('other', 'Other')], max_length=20)),
                ('address', models.TextField()),
                ('size_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tenant_name', models.CharField(blank=True, max_length=200)),
                ('tenant_contact', models.TextField(blank=True)),
                ('lease_start', models.DateField(blank=True, null=True)),
                ('lease_end', models.DateField(blank=True, null=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shop_type', models.CharField(choices=[('retail', 'Retail Shop'), ('food', 'Food Vendor'), ('service', 'Service Provider'), ('other', 'Other')], max_length=20)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('contact_info', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lease_start', models.DateField(blank=True, null=True)),
                ('lease_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
