# Generated by Django 4.1.13 on 2025-12-13 16:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('qualifications', models.TextField(blank=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='membership.member')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('grade_level', models.CharField(choices=[('preschool', 'Preschool'), ('kindergarten', 'Kindergarten'), ('elementary', 'Elementary'), ('middle', 'Middle School'), ('high', 'High School'), ('adult', 'Adult Education')], max_length=20)),
                ('subject', models.CharField(choices=[('quran', 'Quran Studies'), ('arabic', 'Arabic Language'), ('islamic_studies', 'Islamic Studies'), ('hadith', 'Hadith'), ('fiqh', 'Fiqh'), ('seerah', 'Seerah'), ('other', 'Other')], max_length=20)),
                ('max_students', models.PositiveIntegerField(default=20)),
                ('description', models.TextField(blank=True)),
                ('schedule', models.TextField(blank=True, help_text='Class schedule details')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='education.teacher')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('transferred', 'Transferred')], default='active', max_length=20)),
                ('grade', models.CharField(blank=True, help_text='Current grade/mark', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='education.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='membership.member')),
            ],
            options={
                'ordering': ['-enrollment_date'],
                'unique_together': {('student', 'class_instance')},
            },
        ),
    ]
