# Generated by Django 4.2.27 on 2026-01-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Unique ID for the teacher', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='office_location',
            field=models.CharField(blank=True, help_text='Office or desk location', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_email',
            field=models.EmailField(blank=True, help_text='Official work email', max_length=254),
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_phone',
            field=models.CharField(blank=True, help_text='Official work phone', max_length=20),
        ),
    ]
