# Generated by Django 4.2.27 on 2026-01-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_teacher_bio_teacher_employee_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='hire_date',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='specialization',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='member',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='office_location',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='work_email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='work_phone',
        ),
        migrations.AddField(
            model_name='teacher',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='father_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='general_qualification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='house_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='islamic_qualification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='land_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='lsg_name',
            field=models.CharField(blank=True, help_text='Panchayath/Municipality/Corporation', max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='membership_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='organization',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('other', 'Other')], default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pin_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='post_office',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_level',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('higher_secondary', 'Higher Secondary'), ('other', 'Other')], max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='unit_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='unit_secretary_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='unit_secretary_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='via',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
