# Generated by Django 4.2.27 on 2026-01-09 17:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_rename_hire_date_teacher_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='course_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total fee for this course', max_digits=10),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('exempt', 'Exempt')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reference_number', models.CharField(blank=True, help_text='Receipt No / Transaction ID', max_length=100)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('check', 'Check'), ('other', 'Other')], default='cash', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='education.studentenrollment')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
