# Generated by Django 4.2.27 on 2026-01-18 16:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0017_houseregistration_area'),
        ('education', '0004_class_course_fee_studentenrollment_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled')], default='pending', max_length=20)),
                ('admission_number', models.CharField(blank=True, help_text='Auto-generated admission ID', max_length=50, unique=True)),
                ('documents_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('incomplete', 'Incomplete')], default='pending', max_length=20)),
                ('documents_remarks', models.TextField(blank=True, help_text='Notes about submitted documents')),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_remarks', models.TextField(blank=True)),
                ('parent_contact', models.CharField(blank=True, max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('special_requirements', models.TextField(blank=True, help_text='Any special requirements or needs')),
                ('approved_by', models.CharField(blank=True, help_text='Name of person who approved', max_length=200)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, help_text='General remarks about admission')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_applied', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_applications', to='education.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='membership.member')),
            ],
            options={
                'verbose_name': 'Student Admission',
                'verbose_name_plural': 'Student Admissions',
                'ordering': ['-admission_date'],
            },
        ),
    ]
