# Generated by Django 4.2.27 on 2026-03-04 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_add_name_to_transaction'),
        ('education', '0005_studentadmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeepayment',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_payment', to='accounting.transaction'),
        ),
    ]
