# Generated by Django 4.2.27 on 2025-12-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='module_assets_enabled',
            field=models.BooleanField(default=True, help_text='Enable Assets module'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='module_committee_enabled',
            field=models.BooleanField(default=True, help_text='Enable Committee & Minutes module'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='module_education_enabled',
            field=models.BooleanField(default=True, help_text='Enable Education module'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='module_finance_enabled',
            field=models.BooleanField(default=True, help_text='Enable Finance module'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='module_hr_enabled',
            field=models.BooleanField(default=True, help_text='Enable HR & Payroll module'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='module_membership_enabled',
            field=models.BooleanField(default=True, help_text='Enable Membership Management module'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='module_operations_enabled',
            field=models.BooleanField(default=True, help_text='Enable Operations module'),
        ),
    ]
