# Generated by Django 4.2.27 on 2025-12-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_systemsettings_module_assets_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('executive', 'Executive Board Member'), ('staff', 'Staff Member')], default='staff', max_length=20),
        ),
    ]
