# Generated by Django 4.2.27 on 2025-12-22 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('home', '0006_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_modules', models.JSONField(blank=True, default=list, help_text='Modules accessible to Administrators (in addition to CMS)')),
                ('executive_modules', models.JSONField(blank=True, default=list, help_text='Modules accessible to Executive Board Members')),
                ('staff_modules', models.JSONField(blank=True, default=list, help_text='Modules accessible to Staff Members')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
