# Generated by Django 4.2.27 on 2025-12-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_accesscontrolsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrolsettings',
            name='admin_modules',
            field=models.JSONField(blank=True, default=list, help_text='Modules accessible to Administrators (in addition to CMS)', null=True),
        ),
        migrations.AlterField(
            model_name='accesscontrolsettings',
            name='executive_modules',
            field=models.JSONField(blank=True, default=list, help_text='Modules accessible to Executive Board Members', null=True),
        ),
        migrations.AlterField(
            model_name='accesscontrolsettings',
            name='staff_modules',
            field=models.JSONField(blank=True, default=list, help_text='Modules accessible to Staff Members', null=True),
        ),
    ]
