# Generated by Django 4.2.27 on 2025-12-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_accesscontrolsettings_admin_modules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='module_accounting_enabled',
            field=models.BooleanField(default=True, help_text='Enable Accounting & Ledger module'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='module_billing_enabled',
            field=models.BooleanField(default=True, help_text='Enable Billing & Invoices module'),
        ),
    ]
