# Generated by Django 4.2.27 on 2026-01-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DigitalSignageContent',
        ),
        migrations.DeleteModel(
            name='PrayerTime',
        ),
    ]
