# Generated by Django 4.2.27 on 2026-01-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the person/entity related to this transaction', max_length=200),
        ),
    ]
